openapi: 3.0.0
info:
  title: URL Shortener API
  version: 1.0.0
paths:
  /shorten:
    post:
      summary: Shorten a URL
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                long_url:
                  type: string
              required:
                - long_url
      responses:
        '201':
          description: Shortened URL created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  short_url:
                    type: string
        '400':
          description: Bad Request, invalid input
  '/{short_url}':
    get:
      summary: Retrieve the original URL
      parameters:
        - name: short_url
          in: path
          required: true
          description: The shortened URL
          schema:
            type: string
      responses:
        '200':
          description: Original URL retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  long_url:
                    type: string
        '404':
          description: Shortened URL not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Shortened URL not found
